import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserDataProvider } from "./contexts/user-data-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "🚀 Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDataProvider>{children}</UserDataProvider>
      </body>
    </html>
  );
}
